version: "3.7"
services:
    database:
        build: ./database
        ports:
            - 3306:3306

    backend:
        build: 
            context: ./backend
            target: prod
        ports:
            - 5001:8080
            - 5678:5678
        depends_on:
            - database

    frontend:
        build: ./frontend
        ports:
            - 5000:3000
        depends_on:
            - backend
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - /app/.next