version: "3.7"
services:

    database:
        platform: linux/x86_64
        container_name: database
        build: ./database
        ports:
            - 3306:3306
        networks:
            - mtp

    backend:
        container_name: backend
        build: 
            context: ./backend
            target: prod
        ports:
            - 5001:8080
            - 5678:5678
        depends_on:
            - database
        networks:
            - mtp

    frontend:
        container_name: frontend
        build: ./frontend
        target: production
        depends_on:
            - backend
        networks:
            - mtp
        ports:
            - 80:3000

    # e2e:
    #     image: cypress
    #     build: ./e2e
    #     container_name: cypress
    #     depends_on:
    #         - frontend
    #     # note: inside e2e container, the network allows accessing
    #     # "frontend" host under name "frontend"
    #     # so "curl http://frontend" would return whatever the frontendserver
    #     # in the "frontend" container is cooking
    #     # see https://docs.docker.com/compose/networking/
    #     environment:
    #         - CYPRESS_baseUrl=http://frontend:3000
    #     command: npx cypress run
    #     # mount the host directory e2e/cypress and the file e2e/cypress.json as
    #     # volumes within the container
    #     # this means that:
    #     #  1. anything that Cypress writes to these folders (e.g., screenshots,
    #     #     videos) appears also on the Docker host's filesystem
    #     #  2. any change that the developer applies to Cypress files on the host
    #     #     machine immediately takes effect within the e2e container (no docker
    #     #     rebuild required).
    #     networks:
    #         - mtp
    #     volumes:
    #         - ./e2e/cypress:/app/cypress
    #         - ./e2e/cypress.json:/app/cypress.json

    # rabbitmq:
    #     container_name: rabbitmq
    #     build: ./utils/rabbitmq
    #     hostname: localhost
    #     ports:
    #         - 5672:5672
    #     networks:
    #         - mtp

#     elasticsearch:
#         container_name: elasticsearch
#         build: ./utils/elasticsearch
#         volumes:
#             - type: bind
#               source: ./utils/elasticsearch/config/elasticsearch.yml
#               target: /usr/share/elasticsearch/config/elasticsearch.yml
#               read_only: true
#             - type: volume
#               source: elasticsearch
#               target: /usr/share/elasticsearch/data
#         ports:
#             - "9200:9200"
#             - "9300:9300"
#         environment:
#             ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#             ELASTIC_PASSWORD: elastic
#             discovery.type: single-node
#         networks:
#             - mtp
    
#     logstash:
#         container_name: logstash
#         build: ./utils/logstash
#         volumes:
#             - type: bind
#               source: ./utils/logstash/config/logstash.yml
#               target: /usr/share/logstash/config/logstash.yml
#               read_only: true
#             - type: bind
#               source: ./utils/logstash/pipeline
#               target: /usr/share/logstash/pipeline
#               read_only: true
#         ports:
#             - "5044:5044"
#             - "5000:5000/tcp"
#             - "5000:5000/udp"
#             - "9600:9600"
#         environment:
#             LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#         networks:
#             - mtp
#         depends_on:
#             - elasticsearch
    
#     kibana:
#         container_name: kibana
#         build: ./utils/kibana/
#         volumes:
#             - type: bind
#               source: ./utils/kibana/config/kibana.yml
#               target: /usr/share/kibana/config/kibana.yml
#               read_only: true
#         ports:
#             - "5601:5601"
#         networks:
#             - mtp
#         depends_on:
#             - elasticsearch

# configs:
#     elastic_config:
#         file: ./utils/elasticsearch/config/elasticsearch.yml
#     logstash_config:
#         file: ./utils/logstash/config/logstash.yml
#     logstash_pipeline:
#         file: ./utils/logstash/pipeline/logstash.conf
#     kibana_config:
#         file: ./utils/kibana/config/kibana.yml


networks:
    mtp:
      name: mtp

# volumes:
#     elasticsearch:


