version: "3.7"
services:
  backend:
    platform: linux/x86_64
    container_name: backend
    build:
      context: ./backend
    ports:
      - 5001:8080
    networks:
      - mtp

  # prometheus:
  #   container_name: prometheus
  #   build: ./prometheus
  #   ports:
  #     - 9090:9090
  #   depends_on:
  #     - backend
  #   networks:
  #     - mtp

  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - mtp

  nlp:
    container_name: nlp
    build: ./nlp
    ports:
      - 5000:5000

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: production
    networks:
      - mtp
    ports:
      - 3000:3000

networks:
  mtp:
    name: mtp
