import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Button } from 'antd'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MedicalTextPlatform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">MedicalTextPlatform!</a>
        </h1>
        <Button type="primary">Button</Button>
      </main>
    </div>
  )
}
