import Head from 'next/head'
import styles from '../Home.module.css'
import { Card, Col, Row } from 'antd'
import SignUpForm from '../../components/SignUpForm/SignUpForm'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MedicalTextPlatform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>MedicalTextPlatform</h1>
      <main className={styles.main}>
        <Row gutter={128}>
          <Col span={12}>
            <Card title="Stwórz konto">
              <p>Stwórz konto aby skorzystać z serwisu.</p>
            </Card>
          </Col>
          <Col span={12}>
            <SignUpForm />
          </Col>
        </Row>
      </main>
    </div>
  )
}
