# This is a basic workflow to help you get started with Actions

name: MTP Build&Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the frontend container
  build-frontend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Lint, test and build the image
        run: docker-compose up --build frontend

      - name: Login to TreeScale
        uses: docker/login-action@v1
        with:
          registry: repo.treescale.com
          username: ${{ secrets.TREESCALE_USERNAME }}
          password: ${{ secrets.TREESCALE_PASSWORD }}

      - name: Tag image
        run: docker tag medical-text-platform_frontend:latest repo.treescale.com/lukasz-starosta/medical-text-platform:latest
      
      - name: Push image to TreeScale
        run: docker push repo.treescale.com/lukasz-starosta/medical-text-platform:latest